<?php 

/**
 * @file
 * Provides flip counter functionality.
 */


/**
 * Implements hook_theme().
 */
function flipcounter_theme() {
  return array(
    'flipcounter' => array(
      'arguments' => array('name' => NULL, 'value' => NULL, 'options' => array()),
      'template' => 'flipcounter',
      'path' => drupal_get_path('module', 'flipcounter') . '/theme',
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Adds required CSS/JavaScript files.
 */
function flipcounter_add() {
  static $added;

  // Add CSS/JavaScript files if needed.
  if ( !isset($added) ) {
    // Add files from library.
    drupal_add_css(libraries_get_path('flipcounter') . '/css/counter.css');
    drupal_add_js(libraries_get_path('flipcounter') . '/js/flipcounter.min.js');

    // Add module css and javascript files.
    drupal_add_css(drupal_get_path('module', 'flipcounter') . '/flipcounter.css');
    drupal_add_js(drupal_get_path('module', 'flipcounter') . '/flipcounter.js');

    $added = TRUE;
  }
}
